apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: lab2-app
    component: application
    service: flask-app
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080
  selector:
    app: lab2-app
    component: application

