apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
  labels:
    app: flask-app
    component: config
    environment: production
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  OUTPUT_DIR: "/app/data"

